-- BẮT BUỘC: Bật extension vector để lưu trữ gemini_vector(768)
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- ENUM TYPES
-- ============================================
CREATE TYPE user_status AS ENUM ('ACTIVE', 'BANNED');
CREATE TYPE gender_type AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE role_type AS ENUM ('TRAVELER', 'PROVIDER', 'ADMIN');
CREATE TYPE place_status_enum AS ENUM ('OPERATIONAL', 'TEMPORARILY_CLOSED', 'PERMANENTLY_CLOSED');
CREATE TYPE media_type_enum AS ENUM ('IMAGE', 'VIDEO');
CREATE TYPE poi_type_enum AS ENUM ('ATTRACTION', 'NATURE', 'RELIGIOUS', 'NIGHTLIFE', 'SHOPPING', 'CAFE_DESSERT', 'STREET_FOOD', 'RESTAURANT', 'OTHER');
CREATE TYPE poi_status_enum AS ENUM ('ACTIVE', 'BANNED');
CREATE TYPE review_status_enum AS ENUM ('ACTIVE', 'BANNED');
CREATE TYPE post_status AS ENUM ('PUBLISHED', 'ARCHIVED', 'BANNED');
CREATE TYPE itinerary_status_enum AS ENUM ('PLANNING', 'ONGOING', 'COMPLETED', 'CANCELLED');
CREATE TYPE auth_provider AS ENUM ('LOCAL', 'GOOGLE');
CREATE TYPE role_conversation AS ENUM ('MEMBER', 'ADMIN');
CREATE TYPE conversation_type AS ENUM ('PRIVATE', 'GROUP');
CREATE TYPE experience_category AS ENUM ('PHOTO', 'FOOD', 'NIGHTLIFE', 'LOCAL_CULTURE', 'COUPLE', 'FAMILY');
-- CREATE TYPE report_reason_enum AS ENUM (
--     'SPAM', 'HARASSMENT', 'HATE_SPEECH', 'FALSE_INFORMATION', 'INAPPROPRIATE_CONTENT','INTELLECTUAL_PROPERTY_INFRINGEMENT', 'OTHER'
-- );
-- CREATE TYPE report_target_type_enum AS ENUM ('POST', 'REVIEW');
-- CREATE TYPE report_status_enum AS ENUM ('PENDING', 'RESOLVED', 'REJECTED');

-- TABLES

-- ============================================
-- USERS & ROLES
-- ============================================

CREATE TABLE media (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   url TEXT NOT NULL,
   type media_type_enum NOT NULL,
   cloud_name TEXT UNIQUE,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    role role_type,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255),
    email VARCHAR(100) UNIQUE,
    full_name VARCHAR(100),
    gender gender_type,
    dob DATE,
    status user_status NOT NULL DEFAULT 'ACTIVE',
    avatar_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    cover_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    auth_provider auth_provider DEFAULT 'LOCAL',
    google_id VARCHAR(255) UNIQUE,
    follower_count BIGINT NOT NULL DEFAULT 0, -- nguoi ma theo doi minh
    following_count BIGINT NOT NULL DEFAULT 0, -- nguoi ma minh thoi doi
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);
CREATE TABLE admin (
    id BIGSERIAL PRIMARY KEY,
    CONSTRAINT fk_admin_users FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE

);
CREATE TABLE traveler (
    id BIGSERIAL PRIMARY KEY,
    CONSTRAINT fk_traveler_users FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE provider (
    id BIGSERIAL PRIMARY KEY,
    phone_number VARCHAR(10) UNIQUE,
    address TEXT,
    business_name VARCHAR(100),
    CONSTRAINT fk_provider_users FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_profile_vector (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    profile_vector vector(768),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- PLACE & WARD & MEDIA
-- ============================================
CREATE TABLE place (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    city_code VARCHAR(50),
    codename VARCHAR(50),
    country VARCHAR(100),
    country_code VARCHAR(10),
    region VARCHAR(100),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    google_place_id VARCHAR(255)
);

CREATE TABLE ward (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) UNIQUE,
    division_type VARCHAR(50),
    codename VARCHAR(50),
    place_id BIGINT REFERENCES place(id) ON DELETE CASCADE,
    description TEXT,
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE
);

-- ============================================
-- PLACE OF INTEREST
-- ============================================
CREATE TABLE place_of_interest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    poi_type poi_type_enum,
    poi_type_detail TEXT,
    system_status poi_status_enum DEFAULT 'ACTIVE' NOT NULL,
    address TEXT,
    website TEXT,
    phone_number VARCHAR(20),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    rating DECIMAL(3, 2),
    review_count INT,
    status place_status_enum NOT NULL DEFAULT 'OPERATIONAL',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    google_maps_url TEXT,
    description TEXT,
    google_place_id VARCHAR(255) UNIQUE,
    opening_hour JSONB,
    reviews_distribution JSONB,
    additional_info JSONB,
    price_min BIGINT,
    price_max BIGINT,
    place_id BIGINT REFERENCES place(id) ON DELETE SET NULL,
    ward_id BIGINT REFERENCES ward(id) ON DELETE SET NULL,
    semantic_text TEXT,
    gemini_vector vector(768),
    description_vector vector(768)
);

CREATE TABLE poi_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_of_interest_id BIGINT NOT NULL REFERENCES place_of_interest(id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL,
    open_time TIME NOT NULL,
    close_time TIME NOT NULL,
    CONSTRAINT fk_poi_hours_poi
        FOREIGN KEY (place_of_interest_id)
        REFERENCES place_of_interest(id)
        ON DELETE CASCADE
);

-- ============================================
-- REVIEW
-- ============================================
CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_review_id VARCHAR(255) UNIQUE, --
    status review_status_enum not null default 'ACTIVE',
    content TEXT, --
    rating DECIMAL(3, 2), --
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, --
    updated_at TIMESTAMP,
    external_name VARCHAR(255), --
    external_avt TEXT, --
    is_crawled BOOLEAN NOT NULL DEFAULT FALSE, --
    place_of_interest_id BIGINT REFERENCES place_of_interest(id) ON DELETE SET NULL,
    traveler_id BIGINT REFERENCES traveler(id) ON DELETE SET NULL
);

-- ============================================
-- SOCIAL (POSTS, COMMENTS, REACTIONS, FOLLOW)
-- ============================================
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    title VARCHAR(255),
    poi_id BIGINT REFERENCES place_of_interest(id) ON DELETE SET NULL,
    topic_tag VARCHAR(255),
    content TEXT,
    status post_status NOT NULL DEFAULT 'PUBLISHED',
    folder_id  UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    published_at TIMESTAMP
);

CREATE TABLE comment (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    parent_comment_id BIGINT REFERENCES comment(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE reactions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,

    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    comment_id BIGINT REFERENCES comment(id) ON DELETE CASCADE,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE (post_id, user_id)
);

CREATE TABLE follow (
    follower_id BIGINT REFERENCES users(id) ON DELETE CASCADE, -- ban than nguoi theo doi
    following_id BIGINT REFERENCES users(id) ON DELETE CASCADE, -- nguoi duoc theo doi
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (follower_id, following_id)
);

-- ============================================
-- OAUTH TOKENS
-- ============================================
CREATE TABLE user_oauth_tokens (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    provider VARCHAR(50) DEFAULT 'GOOGLE',
    access_token TEXT,
    refresh_token TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- ============================================
-- ITINERARY & ITINERARY ACTIVITY
-- ============================================
CREATE TABLE itinerary (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    styles JSONB,
    destination_cities JSONB,
    user_notes TEXT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    budget NUMERIC(12, 2),
    has_kids BOOLEAN,
    has_pets BOOLEAN,
    companion VARCHAR(255),
    objectives TEXT,
    status itinerary_status_enum NOT NULL DEFAULT 'PLANNING',
    traveler_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6),

    -- Các cột lấy từ lệnh ALTER TABLE
    estimated_total_price NUMERIC(12, 2),
    estimated_transportation_price NUMERIC(12, 2),
    estimated_activity_price NUMERIC(12, 2),
    estimated_food_and_drink_price NUMERIC(12, 2),
    estimated_accommodation_price NUMERIC(12, 2),
    estimated_currency VARCHAR(10),

    CONSTRAINT fk_itinerary_users FOREIGN KEY (traveler_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE itinerary_activity (
    id BIGSERIAL PRIMARY KEY,
    description TEXT,
    start_time TIME(6),
    end_time TIME(6),
    time_of_day VARCHAR(50),
    type poi_type_enum,
    note TEXT,
    activity_cost NUMERIC(10, 2),
    transportation_cost NUMERIC(10, 2),
    itinerary_date DATE NOT NULL,
    itinerary_id BIGINT NOT NULL,
    poi_id BIGINT,

    CONSTRAINT fk_activity_itinerary FOREIGN KEY (itinerary_id) REFERENCES itinerary(id) ON DELETE CASCADE,
    CONSTRAINT fk_activity_poi FOREIGN KEY (poi_id) REFERENCES place_of_interest(id) ON DELETE SET NULL
);

CREATE TABLE itinerary_shared_user (
    itinerary_id BIGINT REFERENCES itinerary(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    PRIMARY KEY (itinerary_id, user_id)
);

-- ============================================
-- CONVERSATION & MESSAGE
-- ============================================
CREATE TABLE conversation (
    id BIGSERIAL PRIMARY KEY,
    group_name VARCHAR(255),
    group_avatar_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    type conversation_type NOT NULL DEFAULT 'PRIVATE',
    last_message_at TIMESTAMPTZ DEFAULT NOW(),
    last_message_content TEXT,
    last_message_sender_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE conversation_members (
    conversation_id BIGINT REFERENCES conversation(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    role role_conversation NOT NULL DEFAULT 'MEMBER',
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    cleared_at TIMESTAMPTZ DEFAULT NULL,
    PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE message (
    id BIGSERIAL PRIMARY KEY,
    conversation_id BIGINT REFERENCES conversation(id) ON DELETE CASCADE,
    sender_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- ============================================
-- MEDIA RELATIONS (JUNCTION TABLES)
-- ============================================
CREATE TABLE media_review (
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    review_id BIGINT REFERENCES review(id) ON DELETE CASCADE,
    PRIMARY KEY (media_id, review_id)
);

CREATE TABLE media_poi (
    place_of_interest_id BIGINT REFERENCES place_of_interest(id) ON DELETE CASCADE,
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    PRIMARY KEY (place_of_interest_id, media_id)
);

CREATE TABLE media_posts (
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, media_id)
);

CREATE TABLE media_comment (
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    comment_id BIGINT REFERENCES comment(id) ON DELETE CASCADE,
    PRIMARY KEY (media_id, comment_id)
);

CREATE TABLE media_message (
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    message_id BIGINT REFERENCES message(id) ON DELETE CASCADE,
    PRIMARY KEY (media_id, message_id)
);

-- ============================================
-- NOTIFICATION
-- ============================================
CREATE TABLE notification (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- ============================================
-- POST STATUS HISTORY (LOG FOR POST STATUS CHANGE)
-- ============================================
CREATE TABLE post_status_history (
    id BIGSERIAL PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    admin_id BIGINT NOT NULL REFERENCES users(id) ON DELETE SET NULL,
    old_status VARCHAR(50) NOT NULL,
    new_status VARCHAR(50) NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================
-- REPORT POSTS
-- ============================================
CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_type VARCHAR(50) NOT NULL,

    -- LÝ DO CỐ ĐỊNH & CHI TIẾT
    reason VARCHAR(255) NOT NULL,
    reason_detail TEXT,

    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',

    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    -- review_id BIGINT REFERENCES review(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP

    -- CONSTRAINT chk_report_target_exclusive CHECK (
    --     (target_type = 'POST' AND post_id IS NOT NULL AND review_id IS NULL) OR
    --     (target_type = 'REVIEW' AND review_id IS NOT NULL AND post_id IS NULL)
    -- )
);

-- 3. Bảng trung gian lưu File minh chứng
CREATE TABLE media_reports (
    report_id BIGINT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media(id) ON DELETE CASCADE,
    PRIMARY KEY (report_id, media_id)
);

-- ============================================
-- INDEXES OPTIMIZATION
-- ============================================
CREATE INDEX idx_users_fullname_lower ON users (LOWER(full_name));
CREATE INDEX idx_posts_status_created ON posts (status, created_at DESC);
CREATE INDEX idx_poi_place_type_status ON place_of_interest (place_id, poi_type, status);
CREATE INDEX idx_itinerary_traveler_status ON itinerary (traveler_id, status, created_at DESC);
CREATE INDEX idx_comment_post_created ON comment (post_id, created_at ASC);
CREATE INDEX idx_follow_following_id ON follow (following_id);
CREATE INDEX idx_message_conv_created ON message (conversation_id, created_at DESC);
CREATE INDEX idx_conversation_members_user_id ON conversation_members (user_id);

CREATE TABLE poi_experience_insight (
    id BIGSERIAL PRIMARY KEY,
    poi_id BIGINT NOT NULL REFERENCES place_of_interest(id) ON DELETE CASCADE,
    experience_category experience_category NOT NULL,
    mention_count INT DEFAULT 0,
    top_keywords JSONB,
    evidence_count INT DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (poi_id, experience_category)
);

CREATE TABLE itinerary_enhancement_history (
   id BIGSERIAL PRIMARY KEY,
   provider_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
   original_file_name VARCHAR(255),
   provider_prompt TEXT,
   analysis_result JSONB,
   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);