CREATE TYPE user_status AS ENUM ('ACTIVE', 'BANNED');
CREATE TYPE gender_type AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE role_type AS ENUM ('TRAVELER', 'PROVIDER', 'ADMIN');
CREATE TYPE place_status_enum AS ENUM ('OPERATIONAL', 'TEMPORARILY_CLOSED', 'PERMANENTLY_CLOSED');
CREATE TYPE media_type_enum AS ENUM ('IMAGE', 'VIDEO');
CREATE TYPE poi_type_enum AS ENUM ('ATTRACTION', 'NATURE', 'RELIGIOUS', 'NIGHTLIFE', 'SHOPPING', 'CAFE_DESSERT', 'STREET_FOOD', 'RESTAURANT', 'OTHER');
CREATE TYPE poi_status_enum AS ENUM ('ACTIVE', 'BANNED');
CREATE TYPE review_status_enum AS ENUM ('ACTIVE', 'BANNED');
CREATE TYPE post_status AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED', 'BANNED');
CREATE TYPE itinerary_status_enum AS ENUM ('PLANNING', 'ONGOING', 'COMPLETED', 'CANCELLED');
CREATE TYPE auth_provider AS ENUM ('LOCAL', 'GOOGLE');

-- TABLES
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    role role_type,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255),
    email VARCHAR(100) UNIQUE,
    full_name VARCHAR(100),
    gender gender_type,
    dob DATE,
    status user_status NOT NULL DEFAULT 'ACTIVE',
    avatar TEXT,
    provider auth_provider DEFAULT 'LOCAL',
    google_id VARCHAR(255) UNIQUE,
    follower_count BIGINT NOT NULL DEFAULT 0, -- nguoi ma theo doi minh
    following_count BIGINT NOT NULL DEFAULT 0, -- nguoi ma minh thoi doi
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);
CREATE TABLE admin (
    id BIGSERIAL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE

);
CREATE TABLE traveler (
    id BIGSERIAL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE provider (
    id BIGSERIAL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    phone_number VARCHAR(10) UNIQUE,
    address TEXT,
    business_name VARCHAR(100)
);

-- 2. Tạo bảng place
CREATE TABLE place (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    city_code VARCHAR(50),
    codename VARCHAR(50),
    country VARCHAR(100),
    country_code VARCHAR(10),
    region VARCHAR(100),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    google_place_id VARCHAR(255)
);

CREATE TABLE ward (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) UNIQUE,
    division_type VARCHAR(50),
    codename VARCHAR(50),
    place_id BIGINT REFERENCES place(id) ON DELETE CASCADE,
    description TEXT,
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE
)

ALTER TABLE place_of_interest 
ADD COLUMN IF NOT EXISTS ward_id BIGINT REFERENCES ward(id) ON DELETE SET NULL;

-- 3. Tạo bảng place_of_interest
CREATE TABLE place_of_interest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL, --
    poi_type poi_type_enum, --
    poi_type_detail TEXT, --
    system_status poi_status_enum   DEFAULT 'ACTIVE' NOT NULL, -- 'active' or 'banned'
    address TEXT, --
    website TEXT, --
    phone_number VARCHAR(20), --
    latitude  DECIMAL(10, 8), --
    longitude DECIMAL(11, 8), --
    rating DECIMAL(3, 2), --
    review_count INT, --
    status place_status_enum NOT NULL DEFAULT 'OPERATIONAL', --
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, --
    updated_at TIMESTAMP,
    google_maps_url TEXT, -- Còn image_url (nó sẽ nằm bên media table)
    description TEXT, --
    google_place_id VARCHAR(255) UNIQUE, --
    opening_hour JSONB, --
    reviews_distribution JSONB, --
    additional_info JSONB, --
    price_min BIGINT,
    price_max BIGINT,
    place_id BIGINT REFERENCES place(id) ON DELETE SET NULL --
);

CREATE TABLE poi_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_of_interest_id BIGINT NOT NULL REFERENCES place_of_interest(id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL,
    open_time TIME NOT NULL,
    close_time TIME NOT NULL,
    CONSTRAINT fk_poi_hours_poi
        FOREIGN KEY (place_of_interest_id)
        REFERENCES place_of_interest(id)
        ON DELETE CASCADE
);

CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_review_id VARCHAR(255) UNIQUE, --
    status review_status_enum not null default 'ACTIVE',
    content TEXT, --
    rating DECIMAL(3, 2), --
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, --
    updated_at TIMESTAMP,
    external_name VARCHAR(255), --
    external_avt TEXT, --
    is_crawled BOOLEAN NOT NULL DEFAULT FALSE, --
    place_of_interest_id BIGINT REFERENCES place_of_interest(id) ON DELETE SET NULL,
    traveler_id BIGINT REFERENCES traveler(id) ON DELETE SET NULL
);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    title VARCHAR(255),
    content TEXT,
    status post_status NOT NULL DEFAULT 'DRAFT',
    folder_id  UUID NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    published_at TIMESTAMP
);

CREATE TABLE media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    type media_type_enum NOT NULL,
    cloud_name TEXT UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE media_review (
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    review_id BIGINT REFERENCES review(id) ON DELETE CASCADE,
    PRIMARY KEY (media_id, review_id)
);

CREATE TABLE media_poi (
    place_of_interest_id BIGINT REFERENCES place_of_interest(id) ON DELETE CASCADE,
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    PRIMARY KEY (place_of_interest_id, media_id)
);

CREATE TABLE media_posts (
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, media_id)
);

CREATE TABLE follow (
    follower_id BIGINT REFERENCES users(id) ON DELETE CASCADE, -- ban than nguoi theo doi
    following_id BIGINT REFERENCES users(id) ON DELETE CASCADE, -- nguoi duoc theo doi
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (follower_id, following_id)
);

CREATE TABLE user_oauth_tokens (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    provider VARCHAR(50) DEFAULT 'GOOGLE',
    access_token TEXT,
    refresh_token TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

ALTER TABLE admin ADD CONSTRAINT fk_admin_users FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE traveler ADD CONSTRAINT fk_traveler_users FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE provider ADD CONSTRAINT fk_provider_users FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE;

CREATE TABLE itinerary (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    styles JSONB,
    destination_cities JSONB,
    user_notes TEXT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    budget NUMERIC(12, 2),
    has_kids BOOLEAN,
    has_pets BOOLEAN,
    companion VARCHAR(255),
    objectives TEXT,
    status itinerary_status_enum NOT NULL DEFAULT 'PLANNING',
    traveler_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(6),

    CONSTRAINT fk_itinerary_users FOREIGN KEY (traveler_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE itinerary_activity (
    id BIGSERIAL PRIMARY KEY,
    description TEXT,
    start_time TIME(6),
    end_time TIME(6),
    time_of_day VARCHAR(50),
    type poi_type_enum,
    note TEXT,
    activity_cost NUMERIC(10, 2),
    transportation_cost NUMERIC(10, 2),
    itinerary_date DATE NOT NULL,
    itinerary_id BIGINT NOT NULL,
    poi_id BIGINT,

    CONSTRAINT fk_activity_itinerary FOREIGN KEY (itinerary_id) REFERENCES itinerary(id) ON DELETE CASCADE,

    CONSTRAINT fk_activity_poi FOREIGN KEY (poi_id) REFERENCES place_of_interest(id) ON DELETE SET NULL
);

CREATE TABLE comment (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    parent_comment_id BIGINT REFERENCES comment(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE media_comment (
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    comment_id BIGINT REFERENCES comment(id) ON DELETE CASCADE,
    PRIMARY KEY (media_id, comment_id)
);